global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#sergey_gerasimov'
