version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - ${NETWORK}
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${VERSION}
    ports:
      - 9292:${PORT}/tcp
    networks:
      - ${NETWORK}
  post:
    build: ./post-py
    image: ${USERNAME}/post:${VERSION}
    networks:
      - ${NETWORK}
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${VERSION}
    networks:
      - ${NETWORK}

volumes:
  post_db:

networks:
  reddit:
